# Generated by Django 4.1.5 on 2023-01-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Title', models.CharField(max_length=255)),
                ('AnnounceNo', models.BigIntegerField()),
                ('CarRow', models.IntegerField()),
            ],
        ),
    ]
