# Generated by Django 4.1.5 on 2023-01-16 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Title', models.CharField(max_length=255)),
                ('AnnounceNo', models.BigIntegerField()),
                ('CarRow', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SalePlan',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('RegisterStartDate', models.DateTimeField()),
                ('RegisterEndDate', models.DateTimeField()),
                ('LotteryDate', models.DateTimeField()),
                ('Description', models.CharField(max_length=255)),
                ('ExtraDescription', models.TextField()),
                ('LastModifyBy', models.CharField(max_length=255)),
                ('LastModified', models.DateTimeField(auto_now=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
