# Generated by Django 4.1.5 on 2023-01-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleplan',
            name='LotteryDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='saleplan',
            name='RegisterEndDate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='saleplan',
            name='RegisterStartDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
