# Generated by Django 4.1.5 on 2023-01-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0003_alter_saleplan_registerstartdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleplan',
            name='LotteryDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='saleplan',
            name='RegisterEndDate',
            field=models.DateTimeField(),
        ),
    ]
