# Generated by Django 4.1.5 on 2023-01-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0004_alter_saleplan_lotterydate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleplan',
            name='Id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
