# Generated by Django 4.1.5 on 2023-01-18 07:10

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0009_alter_saleplandetail_saleplans_winner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleplan',
            name='RegisterStartDate',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
