# Generated by Django 4.1.5 on 2023-01-18 07:15

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('lottery', '0010_alter_saleplan_registerstartdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleplan',
            name='CreatedAt',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='saleplan',
            name='LastModified',
            field=django_jalali.db.models.jDateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='saleplan',
            name='LotteryDate',
            field=django_jalali.db.models.jDateTimeField(),
        ),
        migrations.AlterField(
            model_name='saleplan',
            name='RegisterEndDate',
            field=django_jalali.db.models.jDateTimeField(),
        ),
    ]
