# Generated by Django 4.1.5 on 2023-01-18 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lottery', '0011_alter_saleplan_createdat_alter_saleplan_lastmodified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleplan',
            name='CreatedAt',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='saleplan',
            name='CreatedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط'),
        ),
        migrations.AlterField(
            model_name='saleplan',
            name='Description',
            field=models.CharField(max_length=255, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='saleplan',
            name='ExtraDescription',
            field=models.TextField(verbose_name='توضیحات اضافی'),
        ),
        migrations.AlterField(
            model_name='saleplan',
            name='LastModified',
            field=django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='saleplan',
            name='LastModifyBy',
            field=models.CharField(max_length=255, verbose_name='اخرین تغییر توسط'),
        ),
        migrations.AlterField(
            model_name='saleplan',
            name='LotteryDate',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ قرعه کشی'),
        ),
        migrations.AlterField(
            model_name='saleplan',
            name='RegisterEndDate',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ پایان ثبت نام'),
        ),
        migrations.AlterField(
            model_name='saleplan',
            name='RegisterStartDate',
            field=django_jalali.db.models.jDateTimeField(verbose_name='تاریخ شروع ثبت نام'),
        ),
    ]
